# Generated by Django 3.1.7 on 2021-03-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32, verbose_name='Город')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('email', models.CharField(max_length=128, verbose_name='Почта')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
            ],
        ),
    ]
